//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignmentfive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSummary
    {
        public int OrderSummaryID { get; set; }
        public string O_Name { get; set; }
        public string BookName { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> B_id { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
